### ISSUE TITLE
dbs api not reachable if libs are outside from CMSSW

### ISSUE THREAD

**Issue by padeken** [Aachen-3A/libs3a#1]
from dbs.apis.dbsClient import DbsApi
ImportError: No module named dbs.apis.dbsClient

WTF?

**Comment by tobias-pook** [comment]
I can not reproduce your issue. CMSSW needs to be sourced but it is not mandatory to place the libs folder in the CMSSW src path.
I created the following 2 line testscript and attached the shell output:

```
import dbutilscms
print "test"
```

```
$ pwd
/.automount/home/home__home1/institut_3a/pook/repos/localCopies/TAPAS/libs3a/python
$ python testDButils.py
test
```

P.S. A hint which lib caused the issue is a good idea for an issue report.

**Comment by padeken** [comment]
source /afs/cern.ch/cms/ccs/wm/scripts/Crab/crab.sh
